### ISSUE TITLE
API key is public!!

### ISSUE THREAD

**Issue by LaLeonie** [fac18/week5-EIJO-weatherAPI#32]
Alarm, alarm, you're API key is public. You always need to make sure that your API key is in a hidden file that is not pushed to github, otherwise, it could get expensive
![](https://media.giphy.com/media/1sd2bQx5GnQf6/giphy.gif)

So instead of storing the API key in config.json, store it in a .env file in the root folder and then make sure that this file is gitignored. 

You'll also need to add some more information about the API to your readme, such as: 
Does the user need an API key? 
How should they set up their API key?

**Comment by marialani** [comment]
We've made a .env file with the keys we previously had in the config.json file
